### ISSUE TITLE
`udata search reindex` error

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1009]
`udata search reindex` w/o argument raises the following error:

```
Traceback (most recent call last):
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/bin/udata", line 11, in <module>
    load_entry_point('udata', 'console_scripts', 'udata')()
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/__init__.py", line 88, in console_script
    run_manager()
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/__init__.py", line 84, in run_manager
    manager.run()
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/alexandre/Developer/Etalab/udata/udata/search/commands.py", line 90, in reindex
    if adapter.doc_type().lower() == doc_type.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by abulte** [comment]
Fixed in `1.1.0`
