### ISSUE TITLE
ERROR in app: Exception on /fr/register [POST]

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1247]
Hi everyone

I installed the new version udata 1.2.3 and when I test the registration of a new user I get an internal error.

![image](https://user-images.githubusercontent.com/30826928/32161197-f71300c2-bd54-11e7-8b78-f961989f022b.png)

**udata-front.log**

```
[2017-10-30 09:26:03,446] ERROR in app: Exception on /fr/register [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_security/decorators.py", line 230, in wrapper
    return f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_security/views.py", line 118, in register
    user = register_user(**form.to_dict())
  File "/srv/udata/local/lib/python2.7/site-packages/flask_security/registerable.py", line 41, in register_user
    'welcome', user=user, confirmation_link=confirmation_link)
  File "/srv/udata/local/lib/python2.7/site-packages/celery/app/task.py", line 413, in delay
    return self.apply_async(args, kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/celery/app/task.py", line 536, in apply_async
    **options
  File "/srv/udata/local/lib/python2.7/site-packages/celery/app/base.py", line 737, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/srv/udata/local/lib/python2.7/site-packages/celery/app/amqp.py", line 554, in send_task_message
    **properties
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/utils/json.py", line 72, in dumps
    **dict(default_kwargs, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/srv/udata/local/lib/python2.7/site-packages/simplejson/encoder.py", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/srv/udata/local/lib/python2.7/site-packages/simplejson/encoder.py", line 373, in iterencode
    return _iterencode(o, 0)
  File "/srv/udata/local/lib/python2.7/site-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/srv/udata/local/lib/python2.7/site-packages/simplejson/encoder.py", line 268, in default
    raise TypeError(repr(o) + " is not JSON serializable")
EncodeError: <User: test test> is not JSON serializable
```

**Comment by abulte** [comment]
Hi @damonzon33, thanks for the report. I can reproduce this, we'll look into it.

**Comment by damonzon33** [comment]
thanks @abulte

**Comment by damonzon33** [comment]
Hi @abulte
I see that this issue  has been solved, can I install the version 1.2.3 again  or do I have to wait for a new version?

**Comment by abulte** [comment]
@damonzon33 you have to wait for the next release (or install from `master`).

**Comment by damonzon33** [comment]
thanks @abulte
