### ISSUE TITLE
Erreur 400 Mauvaise requête / Error 400 bad request #1127

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1365]
Hi,

The problem #1127 is apparently not solved. A user has just created several organizations and can not list them via the site (bad request). If we pass the site in English there is no error.

Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 101, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/spatial/api.py", line 157, in get
    } for id, name in spatial_granularities]
  File "/srv/udata/local/lib/python2.7/site-packages/werkzeug/local.py", line 378, in <lambda>
    __iter__ = lambda x: iter(x._get_current_object())
  File "/srv/udata/local/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/spatial/models.py", line 277, in <lambda>
    lambda: get_spatial_granularities(get_locale()))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_caching/__init__.py", line 674, in decorated_function
    rv = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/spatial/models.py", line 273, in get_spatial_granularities
    return [(id, str(name)) for id, name in granularities]
  File "/srv/udata/local/lib/python2.7/site-packages/speaklater.py", line 133, in __str__
    return str(self.value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 11: ordinal not in range(128)

Version: udata 1.2.5

thanks for your support!

**Comment by damonzon33** [comment]
![image](https://user-images.githubusercontent.com/30826928/34865842-8696d71e-f77a-11e7-8b64-d92fe5e0cf95.png)

![image](https://user-images.githubusercontent.com/30826928/34865859-9d2008fc-f77a-11e7-83e8-562ead1be4a9.png)

**Comment by abulte** [comment]
@damonzon33 thanks for this detailed bug report. We're looking into it.

**Comment by noirbizarre** [comment]
I'm reproducing this bug on my computer right now so I'm working on this one :+1:

**Comment by damonzon33** [comment]
Update to 1.2.10, the issue is solved

Thank for all
