### ISSUE TITLE
Community resource upload broken 

### ISSUE THREAD

**Issue by petzlux** [opendatateam/udata#1819]
On data.public.lu , I try and create a Community Resource. I get two different errors. 

On initial upload of a `.geojson` file, I get the following error: 

`{"errors": {"filetype": ["URL domain not allowed for filetype file"]}}`

But I still get the resource metadata dialog, where one can set title , description ... 

There I try and upload the same file again, and I get a 500 error (server uwsgi log)

````
[2018-08-06 14:45:46,292] ERROR in app: Exception on /api/1/datasets/community_resources/87263c70-5c42-46d0-bab4-b01c450ced40/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 120, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 320, in post
    infos = self.handle_upload(community.dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 237, in handle_upload
    prefix = '/'.join((dataset.slug,
AttributeError: 'NoneType' object has no attribute 'slug'
````

As a result I cant advance to the final step in the dialog.

**Comment by noirbizarre** [comment]
I need more details: is there any recent changes in the configuration (I think about `CDN_DOMAIN` in particular).

The first error suggest you are missing a domain in [the `RESOURCES_FILE_ALLOWED_DOMAINS` parameter](http://udata.readthedocs.io/en/stable/adapting-settings/#resources_file_allowed_domains). We might need to automatically add the ressources CDN root URL to the whitelisted domains.

The second error indicate that you are trying to **re**upload a file on a community resource not associated with any dataset. This trigger a backend error but the real error seems to be the admin UI which create a new community ressource on error instead of trying to reupload.

**Comment by petzlux** [comment]
Okay that seems to have solved the problem! Cheers!

**Comment by noirbizarre** [comment]
Great !
