### ISSUE TITLE
"dictionary changed size during iteration" while reindexing

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2221]
We regularly have some errors like this when reindexing the database (prod, next, local):

```
➢ Initiliazing index "udata-2019-06-29-15-11"
➢ Indexing Dataset objects
ERROR: dictionary changed size during iteration
➢ Removing index udata-2019-06-29-15-11
```

Tentative fixes were made: https://github.com/opendatateam/udata/pull/2195 and https://github.com/opendatateam/udata/pull/2048 at least but the error keeps popping up.

The last one I tracked seems to be linked to the `last_modified` attribute of a dataset on my local database (a newly "normally" (via web interface) created dataset).

```
Traceback (most recent call last):
  File "/Users/alexandre/Developer/Etalab/udata/udata/search/commands.py", line 142, in handle_error
    yield
  File "/Users/alexandre/Developer/Etalab/udata/udata/search/commands.py", line 194, in index
    index_model(index_name, adapter)
  File "/Users/alexandre/Developer/Etalab/udata/udata/search/commands.py", line 77, in index_model
    for ok, info in streaming_bulk(es.client, docs, raise_on_error=False):
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 161, in streaming_bulk
    for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 55, in _chunk_actions
    for action, data in actions:
  File "/Users/alexandre/Developer/Etalab/udata/udata/search/commands.py", line 59, in iter_for_index
    for doc in docs:
  File "/Users/alexandre/Developer/Etalab/udata/udata/search/commands.py", line 46, in iter_qs
    for obj in qs.no_cache().no_dereference().timeout(False):
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 1491, in __next__
    only_fields=self.only_fields)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/mongoengine/base/document.py", line 698, in _from_son
    copy.deepcopy({'x': fields['last_modified']})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 256, in _deepcopy_dict
    for key, value in x.iteritems():
RuntimeError: dictionary changed size during iteration
```

Note the line where I manually isolate the problematic field (debug):

```
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/mongoengine/base/document.py", line 698, in _from_son
    copy.deepcopy({'x': fields['last_modified']})
```

Since this is a native Mongoengine field, the kind of fix in https://github.com/opendatateam/udata/pull/2048 does not seem appropriate (and probably won't solve the root cause, the error will keep happening on other fields).

The issue is linked to the use of `no_dereference` here https://github.com/opendatateam/udata/blob/master/udata/search/commands.py#L46. A possible solution (it works on local and next) would be to remove the `no_dereference` but:
- it will probably eat up a lot more memory (not such a problem, we do not fully reindex everyday)
- it's quite scary that we can't use `no_dereference` on our objects anymore

**Comment by noirbizarre** [comment]
Without `no_dereference`, indexing does not fit into memory :/ (bad/buggy mongoengine implemention)

**Comment by abulte** [comment]
Reindexation passed on next w/o `no_dereference` last time I tested. Maybe it's better since #2070?

Anyway, if we keep `no_dereference`, what course of action should we take? The fact that it breaks on a native field now seems worrying. Plus we have no guarantee it won't happen on another field.

I do not see a satisfying solution for now, but maybe we can find a root cause to this.

**Comment by noirbizarre** [comment]
If it's working and not too slow without `no_dereference`, let's just make a PR to drop it so the master can work and we will find the root cause in separate issue (let the memory leaks challenge begin)
