### ISSUE TITLE
Metrics: fresh instance crashes on reuses api endpoint

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2524]
Steps to reproduce:
- clone https://github.com/opendatateam/docker-udata
- `cd docker-udata/samples/simple && docker-compose up`
- create an admin user, login
- create a dataset and go to its page in the admin
- the "Reuses" section will crash w/ the following stack trace

Config:

```
udata==2.2.0
udata-ckan==2.0.0
udata-croquemort==2.0.1
udata-geoplatform==2.0.0
udata-gouvfr==2.1.5
udata-ods==2.0.1
udata-piwik==2.1.2
udata-recommendations==2.0.0
```

I'm guessing this happens on any fresh instance, but I've only tested with docker so far.

```
udata_1          | GET /udata/Reuse/_search [status:400 request:0.147s]
udata_1          | [2020-08-12 16:16:09,570] ERROR in app: Exception on /api/1/reuses/ [GET]
udata_1          | Traceback (most recent call last):
udata_1          |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
udata_1          |     rv = self.dispatch_request()
udata_1          |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
udata_1          |     return self.view_functions[rule.endpoint](**req.view_args)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/udata/api/__init__.py", line 122, in wrapper
udata_1          |     return func(*args, **kwargs)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
udata_1          |     resp = resource(*args, **kwargs)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
udata_1          |     return self.dispatch_request(*args, **kwargs)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
udata_1          |     resp = meth(*args, **kwargs)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/marshalling.py", line 243, in wrapper
udata_1          |     resp = f(*args, **kwargs)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/udata/core/reuse/api.py", line 42, in get
udata_1          |     return search.query(ReuseSearch, **multi_to_dict(request.args))
udata_1          |   File "/usr/local/lib/python3.7/site-packages/udata/search/__init__.py", line 234, in query
udata_1          |     return search.execute()
udata_1          |   File "/usr/local/lib/python3.7/site-packages/elasticsearch_dsl/faceted_search.py", line 285, in execute
udata_1          |     return self._s.execute()
udata_1          |   File "/usr/local/lib/python3.7/site-packages/elasticsearch_dsl/search.py", line 627, in execute
udata_1          |     **self._params
udata_1          |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
udata_1          |     return func(*args, params=params, **kwargs)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 539, in search
udata_1          |     doc_type, '_search'), params=params, body=body)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
udata_1          |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 110, in perform_request
udata_1          |     self._raise_error(response.status, raw_data)
udata_1          |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error
udata_1          |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
udata_1          | elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'unknown field [metrics.followers]')
```

**Comment by quaxsze** [comment]
This does not happen if the command `udata init` is ran on a fresh instance, which the doc advices to do. I guess the reindexing is fixing this. Do we want to try to fix this?

**Comment by abulte** [comment]
I guess it spends on _why_ it happens and how difficult it is to fix. I'm not sure a `udata init` should be strictly necessary.

**Comment by quaxsze** [comment]
I think there is globally something on the search method, I get a `TransportError(404, 'index_not_found_exception', 'no such index')` on datasets and organizations list page on a fresh install.

**Comment by abulte** [comment]
Ok, let's say we need an `init`. 👌
