### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2718'

### ISSUE THREAD

**Issue by ycarfantan** [opendatateam/udata#2581]
## Detailed Description

I tried to install udata following [this documentation](https://udata.readthedocs.io/en/latest/development-environment/#development-environment). But I keep having the error `UnicodeEncodeError: 'charmap' codec can't encode character '\u2718' in position 0: character maps to <undefined>` when running a command from the udata CLI (`udata init` for instance).

It's worth noting that I use Python 3.7.6 which seems supported since [this commit](https://github.com/opendatateam/udata/commit/a3ec9d8ad7f789a08c06be53e570774f0411dd7c). The documentation states `virtualenv --python=python2.7 venv`, but it seems that it's not relevant anymore, am I right ?

I think this is a click issue, are you experiencing the same issue ?

## Your Environment

Windows 10 64 bits
Python 3.7.6
Pip freeze : 
```
amqp==2.6.1
aniso8601==8.0.0
appdirs==1.4.4
atomicwrites==1.4.0
attrs==20.3.0
Authlib==0.14.3
awesome-slugify==1.6.5
Babel==2.8.0
bcrypt==3.1.7
billiard==3.6.3.0
bleach==3.1.0
blinker==1.4
celery==4.3.0
celerybeat-mongo==0.2.0
certifi==2020.11.8
cffi==1.14.3
chardet==3.0.4
Click==7.0
colorama==0.4.4
coverage==4.5.4
cryptography==2.8
Cython==0.29.21
dnspython==2.0.0
docutils==0.16
elasticsearch==2.4.1
elasticsearch-dsl==2.2.0
email-validator==1.1.2
entrypoints==0.3
factory-boy==2.12.0
Faker==3.0.0
feedparser==5.2.1
flake8==3.7.8
Flask==1.0.4
Flask-BabelEx==0.9.3
Flask-Caching==1.8.0
Flask-CDN==1.5.3
Flask-Cors==3.0.8
Flask-DebugToolbar==0.10.1
flask-fs==0.6.1
Flask-Gravatar==0.5.0
Flask-Login==0.4.1
Flask-Mail==0.9.1
flask-mongoengine==0.9.5
Flask-Navigation==0.2.0
Flask-Principal==0.4.0
flask-restplus==0.13.0
Flask-Security-Too==3.4.4
Flask-Sitemap==0.3.0
Flask-Themes2==0.1.4
Flask-WTF==0.14.2
geojson==2.5.0
html2text==2019.9.26
httpretty==0.9.7
idna==2.10
importlib-metadata==2.0.0
invoke==1.3.0
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.10.3
jsonschema==3.2.0
keyring==21.5.0
kombu==4.4.0
lxml==4.4.2
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
mock==3.0.5
mongoengine==0.18.2
more-itertools==8.6.0
msgpack==0.6.2
netaddr==0.7.19
packaging==20.4
passlib==1.7.4
Pillow==7.0.0
pkginfo==1.6.1
pluggy==0.13.1
py==1.9.0
pycodestyle==2.5.0
pycparser==2.20
pydenticon==0.3.1
pyflakes==2.1.1
Pygments==2.7.2
pymongo==3.10.1
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==4.6.3
pytest-cov==2.6.1
pytest-env==0.6.2
pytest-flask==0.15.0
pytest-mock==2.0.0
pytest-sugar==0.9.2
python-dateutil==2.8.1
pytz==2019.3
pywin32-ctypes==0.2.0
rdflib==5.0.0
rdflib-jsonld==0.5.0
readme-renderer==28.0
redis==3.3.11
regex==2020.11.13
requests==2.24.0
requests-mock==1.7.0
requests-toolbelt==0.9.1
rfc3986==1.4.0
simplejson==3.17.0
six==1.15.0
speaklater==1.3
StringDist==1.0.9
termcolor==1.1.0
text-unidecode==1.3
tlds==2020111600
tqdm==4.52.0
twine==3.2.0
-e git+https://github.com/opendatateam/udata.git@24a1a2329b9eba3946ab3c1875a4545d08f35755#egg=udata
ujson==1.35
unicodecsv==0.14.1
Unidecode==0.4.21
uritools==3.0.0
urlextract==0.14.0
urllib3==1.25.11
vine==1.3.0
voluptuous==0.11.7
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==0.14.1
WTForms==2.2.1
WTForms-JSON==0.3.3
xmltodict==0.12.0
zipp==3.4.0
zxcvbn==4.4.28
```

Complete stacktrace :
```
Traceback (most recent call last):
  File "D:\projects\DSIC_cartographie\udata\venv\Scripts\udata-script.py", line 11, in <module>
    load_entry_point('udata', 'console_scripts', 'udata')()
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\projects\dsic_cartographie\udata\udata\commands\__init__.py", line 248, in main
    return super(UdataGroup, self).main(*args, **kwargs)
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\flask\cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\flask\cli.py", line 419, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\projects\dsic_cartographie\udata\udata\core\user\commands.py", line 53, in activate
    exit_with_error('Invalid user')
  File "d:\projects\dsic_cartographie\udata\udata\commands\__init__.py", line 70, in exit_with_error
    error(msg, details)
  File "d:\projects\dsic_cartographie\udata\udata\commands\__init__.py", line 65, in error
    echo(format_multiline(msg))
  File "d:\projects\dsic_cartographie\udata\venv\lib\site-packages\click\utils.py", line 260, in echo
    file.write(message)
  File "C:\Users\ycarfantan\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2718' in position 0: character maps to <undefined>
```

**Comment by quaxsze** [comment]
Hello,

Yes Udata does not support python 2 anymore.
This unicode error seems to be a redundant error when trying to use Python on windows 10.
Regarding the click library, the issue might come from one of [these](https://click.palletsprojects.com/en/7.x/wincmd/#unicode-arguments) scenarios
As the documentation states, Udata is made on Unix systems. We cannot guarantee the behaviour on windows systems.
