### ISSUE TITLE
issue with liblzma on pip install

### ISSUE THREAD

**Issue by liblzmasapue** [opendatateam/udata#2595]
Hello,

We've been trying to install udata on an Ubuntu Server 18.04. 

We're following the installation procedure available on readthedocs : https://udata.readthedocs.io/en/stable/system-dependencies/

So far so good, except when, after installing all requirements, we try to install udata through pip : 

`pip install udata`

We're getting an error related to pyliblzma : 

```
    ERROR: Command errored out with exit status 1:
     command: /srv/udata/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gxp0_x6n/pyliblzma_d3f0b8a2bf794aebbe03e5a31527d547/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gxp0_x6n/pyliblzma_d3f0b8a2bf794aebbe03e5a31527d547/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w8ed_db0
         cwd: /tmp/pip-install-gxp0_x6n/pyliblzma_d3f0b8a2bf794aebbe03e5a31527d547/
    Complete output (7 lines):
    /srv/udata/lib/python3.6/site-packages/setuptools/version.py:1: UserWarning: Module lzma was already imported from /usr/lib/python3.6/lzma.py, but /tmp/pip-install-gxp0_x6n/pyliblzma_d3f0b8a2bf794aebbe03e5a31527d547 is being added to sys.path
      import pkg_resources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gxp0_x6n/pyliblzma_d3f0b8a2bf794aebbe03e5a31527d547/setup.py", line 40, in <module>
        for i in xrange(len(c_files)):
    NameError: name 'xrange' is not defined
```
We did upgrade the setuptools but from what I understand, the problem is udata is trying to import a library written for python 2 while a lzma module is already installed with python3 (the 'xrange' undefined error apparently is caused by 'xrange' being a python2 method replaced by just 'range' in python3)

We also tried updating pip but we keep getting the same error.

Has anyone encountered this ?

Thx.

**Comment by abulte** [comment]
Hi, seems like you're trying to use python3.6. We only tested udata2 on python 3.7.

**Comment by dpeterka** [comment]
Also broken in 3.7
```
# pip3 --version
pip 20.2.2 from /usr/lib/python3.7/site-packages/pip (python 3.7)
# pip install pyliblzma
Collecting pyliblzma
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/tmp/pip-install-u_n9ij2h/pyliblzma/setup.py'"'"'; __file__='"'"'/mnt/tmp/pip-install-u_n9ij2h/pyliblzma/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /mnt/tmp/pip-pip-egg-info-2ygsj8md
         cwd: /mnt/tmp/pip-install-u_n9ij2h/pyliblzma/
    Complete output (7 lines):
    /usr/lib/python3.7/site-packages/setuptools/version.py:1: UserWarning: Module lzma was already imported from /usr/lib64/python3.7/lzma.py, but /mnt/tmp/pip-install-u_n9ij2h/pyliblzma is being added to sys.path
      import pkg_resources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-install-u_n9ij2h/pyliblzma/setup.py", line 40, in <module>
        for i in xrange(len(c_files)):
    NameError: name 'xrange' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
```

**Comment by abulte** [comment]
Hi @dpeterka, can you give us the output of `pip install udata` in a fresh virtual env? Thanks.
