### ISSUE TITLE
Specify login/password in udata.cfg when using ES, mongo and redis

### ISSUE THREAD

**Issue by trojette** [opendatateam/udata#881]
## Detailed Description

I want to get `udata` running on Heroku.
Heroku gives me access to `ES`, `mongo` and `redis`, as long as I am able to connect to URLs such as:

```
mongodb://$LOGIN:$PASSWORD@$HOST:$PORT/$LOGIN
redis://$LOGIN:$PASSWORD@$HOST:$PORT/$LOGIN
https://$LOGIN:$PASSWORD@$HOST:$PORT/$LOGIN
http://$LOGIN:$PASSWORD@$HOST:$PORT/$LOGIN
```

Please could you make `udata.cfg` compatible to these URLs format?

**Comment by abulte** [comment]
I did not test this but from what I see in the code, it should be possible with those values:

```
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
MONGODB_SETTINGS = {
    'host': 'mongodb://localhost/database_name'
}
ELASTICSEARCH_URL = 'https://user:secret@other_host:443/production'
```

Please feel free to reopen this issue with further details if it isn't so.

**Comment by trojette** [comment]
Please do test before closing the bug. It doesn't work yet and @noirbizarre confirmed it to me.
Thanks for having a look though.

**Comment by abulte** [comment]
Ok, sorry!

**Comment by trojette** [comment]
Thx!

**Comment by abulte** [comment]
I'll see with @noirbizarre what the exact problem is, but I can confirm those values work on the `dev` branch at least:

```
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
MONGODB_SETTINGS = {
    'host': 'mongodb://localhost:27017/udata'
}
ELASTICSEARCH_URL = 'http://localhost:9200/'
```

**Comment by trojette** [comment]
Do we agree that I want to test this on Heroku with login/password-based services?

**Comment by abulte** [comment]
Yes. Actually, I was thinking the login/password could be the problem.

**Comment by abulte** [comment]
Just to document this issue.

I tested with Heroku ressources. The URLs seem to be correctly parsed but the `udata init` command fails because `eval` is not supported on MongoLabs (seems fair):

```
BROKER_URL = 'redis://h:xxx@ec2-34-250-246-134.eu-west-1.compute.amazonaws.com:12099'
CELERY_RESULT_BACKEND = 'redis://h:xxx@ec2-34-250-246-134.eu-west-1.compute.amazonaws.com:12099'
MONGODB_SETTINGS = {
    'host': 'mongodb://yyy:xxx@ds123662.mlab.com:23662/heroku_3nvjnprl'
}
ELASTICSEARCH_URL = 'https://yyy:xxx@aralia-2079094.eu-west-1.bonsaisearch.net'
```

```
udata init
/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:70: UserWarning: Connecting to aralia-2079094.eu-west-1.bonsaisearch.net using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
-> Apply DB migrations if needed
-> udata:2015-05-06-migrate-issues.js ................................... [Recorded]
Traceback (most recent call last):
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/bin/udata", line 11, in <module>
    load_entry_point('udata', 'console_scripts', 'udata')()
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/__init__.py", line 88, in console_script
    run_manager()
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/__init__.py", line 84, in run_manager
    manager.run()
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/init.py", line 25, in init
    migrate(record=True)
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/db.py", line 165, in migrate
    success &= handler(plugin, filename, script, dryrun=dryrun)
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/db.py", line 105, in record_migration
    db.eval(RECORD_WRAPPER, plugin, filename, script)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 1107, in eval
    result = self.command("$eval", code, args=args)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 494, in command
    codec_options, **kwargs)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on heroku_3nvjnprl to execute command { $eval:
function(plugin, filename, script) {
    db.migrations.insert({
     ..., args: [ "udata", "2015-05-06-migrate-issues.js", "var issues = db.issue.find();

issues.map(function(issue) {
    var title = issue.discussion[0].content;
    title = title.trim().replace('Bonjour..." ] }
```

**Comment by abulte** [comment]
@trojette you can have a look at the `dev` branch if you want for the support of authentification in URLs (#980). We still have a problem on Heroku though, cf #981.

**Comment by noirbizarre** [comment]
Done
