### ISSUE TITLE
Avoid depending on `db.eval` for shared Mongo environments

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#981]
## Detailed Description

As noted on #881, a shared Mongo environment (e.g. Heroku MongoLabs) will complain about not being authorized to run `db.eval` when running `udata init`. This is because `eval` requires admin privilege.

Also, `db.eval` is deprecated since 3.0 https://docs.mongodb.com/manual/reference/method/db.eval/.

## Context

As a user, I want to be able to install `udata` on a shared Mongo instance, for example on Heroku.

## Possible Implementation

Remove the dependency to `db.eval` (used for DB migrations). Investigate https://docs.mongodb.com/manual/reference/method/db.loadServerScripts/.

## Your Environment

`dev` branch, Heroku middlewares.

**Comment by abulte** [comment]
Traceback of the error with Heroku middlewares:

```
udata init
/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:70: UserWarning: Connecting to aralia-2079094.eu-west-1.bonsaisearch.net using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
-> Apply DB migrations if needed
-> udata:2015-05-06-migrate-issues.js ................................... [Recorded]
Traceback (most recent call last):
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/bin/udata", line 11, in <module>
    load_entry_point('udata', 'console_scripts', 'udata')()
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/__init__.py", line 88, in console_script
    run_manager()
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/__init__.py", line 84, in run_manager
    manager.run()
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/init.py", line 25, in init
    migrate(record=True)
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/db.py", line 165, in migrate
    success &= handler(plugin, filename, script, dryrun=dryrun)
  File "/Users/alexandre/Developer/Etalab/udata/udata/commands/db.py", line 105, in record_migration
    db.eval(RECORD_WRAPPER, plugin, filename, script)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 1107, in eval
    result = self.command("$eval", code, args=args)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 494, in command
    codec_options, **kwargs)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on heroku_3nvjnprl to execute command { $eval:
function(plugin, filename, script) {
    db.migrations.insert({
     ..., args: [ "udata", "2015-05-06-migrate-issues.js", "var issues = db.issue.find();

issues.map(function(issue) {
    var title = issue.discussion[0].content;
    title = title.trim().replace('Bonjour..." ] }
```

**Comment by abulte** [comment]
About `db.loadServerScripts`:

1. This solution is valid through the mongo shell on a Heroku database

```
rs-ds123662:PRIMARY> db.system.js.save(    {      _id: "echoFunction",      value : function(x) { return x; }    } )
WriteResult({
	"nMatched" : 0,
	"nUpserted" : 1,
	"nModified" : 0,
	"_id" : "echoFunction"
})
rs-ds123662:PRIMARY> echoFunction(3);
2017-06-16T08:51:30.634+0000 E QUERY    [thread1] ReferenceError: echoFunction is not defined :
@(shell):1:1

rs-ds123662:PRIMARY> db.loadServerScripts()
rs-ds123662:PRIMARY> echoFunction(3)
```

2. Unfortunately, it won't work through `pymongo` since the underlying implementation seems to use `eval`:

```python
db.system.js.save(
    {
        "_id": "echoFunction",
        "value": "function(x) { return x; }"
    }
)

print(db.system_js.echoFunction(4))
```

```
Traceback (most recent call last):
  File "test_mongo.py", line 14, in <module>
    print(db.system_js.echoFunction(4))
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 1167, in <lambda>
    scope={'name': name}), *args)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 1107, in eval
    result = self.command("$eval", code, args=args)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 494, in command
    codec_options, **kwargs)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/alexandre/Developer/Etalab/udata/pyenv/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on heroku_3nvjnprl to execute command { $eval: CodeWScope( function() { return this[name].apply(this, arguments); }, { name: "echoFunction" }), args: [ 4 ] }
```

Docs: http://api.mongodb.com/python/current/api/pymongo/database.html#pymongo.database.SystemJS

**Comment by abulte** [comment]
So @noirbizarre, I guess this leave us only with the option of rewriting all migrations in `pymongo`?

I was thinking of something else: could we plan a version `2.0` starting with a clean migrations slate and from there on use `pymongo` migrations? The migration path for existing instances would be:

1. upgrade to the latest `1.x` and run migrations
2. upgrade to `2.0`

**Comment by abulte** [comment]
This should not be an issue anymore since udata2.
